create table user_cliente_sistema (
	id bigint generated by default as identity,
	
	user_id bigint,
	cliente_sistema_id bigint,

	created_by varchar(255),
	created_date timestamp not null,
	
	primary key (id)
)