create table solicitacao (
	id bigint generated by default as identity,
	
	cliente_id bigint,
	sistema_id bigint,
	user_id bigint,
	descricao varchar(2000) not null,
	prioridade integer,
	status_atual varchar(50),
	
	created_by varchar(255),
	created_date timestamp not null,
	last_modified_by varchar(255),
	last_modified_date timestamp,
	
	primary key (id)
)