create table solicitacao_movimentacao (
	id bigint generated by default as identity,
	
	solicitacao_id bigint,
	observacao varchar(2000),
	status varchar(50) not null,
	
	created_by varchar(255),
	created_date timestamp not null,

	primary key (id)
)