create table sprint (
	id bigint generated by default as identity,

	data_inicio date not null,
	data_fim date not null,
	time_id bigint,
	data_encaminhamento_ao_time timestamp,
	
	created_by varchar(255),
	created_date timestamp not null,
	last_modified_by varchar(255),
	last_modified_date timestamp,
	
	primary key (id)
)