create table sprint_solicitacao (
	id bigint generated by default as identity,
	
	sprint_id bigint,
	solicitacao_id bigint,
	finalizada boolean not null,
	
	created_by varchar(255),
	created_date timestamp,

	primary key (id)
)