create table solicitacao_fase (
	id bigint generated by default as identity,
	
	solicitacao_id bigint,
	fase_id bigint,
	finalizada boolean,
	observacao varchar(2000),
	
	created_by varchar(255),
	created_date timestamp,

	primary key (id)
)