create table pesquisa (
	id bigint generated by default as identity,
	
	class_name varchar(2000) NULL DEFAULT NULL,
	method_name varchar(2000) NULL DEFAULT NULL,
	argumento varchar(2000) NULL DEFAULT NULL,
	retorno varchar(2000) NULL DEFAULT NULL,
	
	created_by varchar(255) NULL DEFAULT NULL,
	created_date TIMESTAMP NOT NULL,

	primary key (id)
)