create table users (
	id bigint generated by default as identity,
	
	user_name varchar(255),
	full_name varchar(255),
	email varchar(255),
	password varchar(255),
	cliente_id bigint,
	ver_outra_solicitacao boolean,

	enabled boolean,
	account_non_expired boolean,
	account_non_locked boolean,
	credentials_non_expired boolean,
	
	created_by varchar(255),
	created_date timestamp not null,
	last_modified_by varchar(255),
	last_modified_date timestamp,

	primary key (id)
)