name: CI/CD FOR PROD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        env:
          JDBC_DATABASE_HOST: ${{ secrets.JDBC_DATABASE_HOST }}
          JDBC_DATABASE_NAME: ${{ secrets.JDBC_DATABASE_NAME }}
          JDBC_DATABASE_USERNAME: ${{ secrets.JDBC_DATABASE_USERNAME }}
          JDBC_DATABASE_PASSWORD: ${{ secrets.JDBC_DATABASE_PASSWORD }}
          SECURITY_JWT_SECRET: ${{ secrets.SECURITY_JWT_SECRET }}
          SECURITY_JWT_EXPIRE: ${{ secrets.SECURITY_JWT_EXPIRE }}
        run: mvn -B package --file pom.xml
      - name: Create build path staging
        run: mkdir staging && cp target/*.jar staging
      - name: Upload math result for job
        uses: actions/upload-artifact@v1
        with:
          name: sca
          path: staging
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: sca-prod-api
        run: heroku plugins:install java && heroku deploy:jar staging/sca-0.0.1-SNAPSHOT.jar --app sca-prod-api
